version: '2'

services:
  redis:
    image: redis:latest
    restart: always
    ports:
     - 6379:6379
  bolt:
    image: fairmont/boltengine
#    build: ./bolt
    restart: always
    expose:
     - 8888
    depends_on:
     - redis
     - rabbitmq
    ports:
     - "8888:8888"
    links:
     - redis
     - rabbitmq
  rabbitmq:
    image: rabbitmq
    restart: always
    expose:
     - 5672
    ports:
     - "5672:5672"
