version: '2'

services:
  redis:
    image: redis:latest
    ports:
     - 6379:6379
  bolt:
    image: b
    restart: always
    expose:
     - 8888
    depends_on:
     - db
     - redis
     - rabbitmq
    ports:
     - "8888:8888"
    links:
     - redis
     - rabbitmq
  rabbitmq:
    image: rabbitmq
    restart: always
    expose:
     - 5672
    ports:
     - "5672:5672"
  db:
    image: amazingfly/postgres
    restart: always
    ports:
     - "5432:5432"
    depends_on:
     - rabbitmq
  wiki:
    image: amazingfly/wiki
    restart: always
    ports:
     - "8181:8181"
  wikiworker:
    image: amazingfly/wikiworker
    restart: always
    depends_on:
     - db
     - rabbitmq
