FROM debian:jessie
MAINTAINER amazingfly <derekstich@gmail.com>

#updates and gets reqired packages
RUN apt-get update -y && \
    apt-get install -y openssl

COPY ./ ./wiki
WORKDIR ./wiki

#creates cert files for https
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout key.pem -out cert.pem -subj "/C=US/ST=North Carolina/L=Winston-Salem/O=CV3/OU=TeamFairmont/CN=192.168.56.103:8181/emailAddress=dstich@commercev3.com"

#port used by serveWiki
EXPOSE 8181

ENTRYPOINT ["./serveWiki"]

