FROM centos:latest
RUN yum install -y openssl
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout key.pem -out cert.pem -subj "/C=US/ST=North Carolina/L=Winston-Salem/O=CV3/OU=TeamFairmont/CN=192.168.56.103:8181/emailAddress=dstich@commercev3.com"
COPY ./ ./
EXPOSE 8181
EXPOSE 8888
ENTRYPOINT ["./serveWiki"]
CMD ["./serveWiki"]
