FROM centos:latest
MAINTAINER amazingfly

ENV BOLT_VERSION 1.1.0
ENV BOLT_URL https://github.com/TeamFairmont/boltengine/releases/download/v$BOLT_VERSION/boltengine-$BOLT_VERSION.tar.gz
ENV APICALLS_URL https://raw.githubusercontent.com/amazingfly/configs/master/apiCalls.json
ENV MQURL '"mqUrl": "amqp://guest:guest@rabbitmq:5672/",'
ENV REDISURL '"host": "redis:6379",'
ENV REDIS_TYPE '"type": "redis",'
ENV STUB_MODE '"stubMode": false,'
ENV HMAC_KEY '"hmackey": "engineadmin_hmackey_goes_here"'

#Download unpack and clean up the bolt engine v1.1.0 release
RUN curl -L -O $BOLT_URL && \
    tar -xzf boltengine*.tar.gz --exclude='*.exe' && \
    rm boltengine*.tar.gz

#tls
RUN yum install -y openssl
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout key.pem -out cert.pem -subj "/C=US/ST=North Carolina/L=Winston-Salem/O=CV3/OU=TeamFairmont/CN=192.168.56.103:8181/emailAddress=dstich@commercev3.com"

#download and put apiCalls.json in extra config directory
RUN curl -L -o /etc/bolt/apiCalls.json $APICALLS_URL

#insert lines into config.json
RUN sed -i '/"engine": {/a \\t"mqUrl": "amqp://guest:guest@rabbitmq:5672/",' /etc/bolt/config.json && \
    sed -i s/'"hmackey": "hmackey1_goes_here"'/"$HMAC_KEY"/g /etc/bolt/config.json && \
    sed -i s/'"stubMode": true,'/"$STUB_MODE"/g /etc/bolt/config.json && \
    sed -i s/'"extraConfigFolder": "etc\/bolt\/",'/'"extraConfigFolder": "\/etc\/bolt",'/g /etc/bolt/config.json && \
    sed -i s/'"host": "localhost:6379",'/"$REDISURL"/g /etc/bolt/config.json && \
    sed -i s/'"type": "",'/"$REDIS_URL"/g /etc/bolt/config.json && \
    sed -i s/'"tlsEnabled": false,'/'"tlsEnabled": true,'/g /etc/bolt/config.json
COPY ./ ./

ENTRYPOINT ./entrypoint.sh

